# Setup
title:               Stefan
tagline:             'Food diaries'
description:         'Reviewing the food that I encounter in my daily life'
url:                 https://stefaneacsu147.github.io
baseurl:             '/food'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Stefan Neacsu
  url:               https://food.neacsustefan.com
  email:             stefaneacsu@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-tagging
  - jekyll-responsive-image
  - jekyll-seo-tag
  - jekyll-analytics
  
# Tagging
tag_page_layout: tag_page
tag_page_dir: tag

# Custom vars
version:             1.0.0

# Analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-117348922-2      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
