# Setup
title:               Stefan
tagline:             'Food diaries'
description:         'Reviewing the food that I encounter in my daily life'
url:                 https://stefaneacsu147.github.io
baseurl:             '/food'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Stefan Neacsu
  url:               https://github.com/stefaneacsu147
  email:             stefaneacsu@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-tagging
  - jekyll-responsive-image
  - jekyll-seo-tag
  
# Tagging
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
